System: 2025-03-09 11:00:10

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -1,18 +1,25 @@
 #!/usr/bin/env bash
 sudo echo "NixOS Rebuilding..."
 
-git add .
+
 
 # Rebuild, output simplified errors, log trackebacks
-sudo nixos-rebuild switch --flake ~/nixos --impure #&> nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)
+sudo nixos-rebuild switch --flake ~/nixos --impure &> nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)
 
-echo "NixOS rebuilt successfully!" 
+if [ $? -eq 1 ]; then
+    echo "NixOS Failed to Rebuild."
+    echo "Please check nixos-switch.log and the error message"
+    exit 1
+fi
+
+echo "NixOS Rebuilt Successfully!" 
 
 read -p "Git Commit and Sync? " user_input
 
 currentDate=$(date +"System: %Y-%m-%d %H:%M:%S")
 
 if [[ $user_input =~ ^[Yy]$ ]]; then
+    git add .
     git commit -m "$currentDate"
     git push origin main
 elif [[ $user_input =~ ^[Nn]$ ]]; then
