SYS: 2025-04-05 22:53:22

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -1,36 +1,37 @@
 #!/usr/bin/env bash
 # Load in the functions and animations
 source assets/bla/bla.sh
-# Run BLA::stop_loading_animation if the script is interrupted
 trap BLA::stop_loading_animation SIGINT
 
 sudo git add .
 
 BLA::start_loading_animation "${BLA_passing_dots[@]}"
-
-# Rebuild, output simplified errors, log trackebacks
-sudo nixos-rebuild switch --flake ~/nixos --impure &> nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)
+    sudo nixos-rebuild switch --flake ~/nixos --impure &> nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)
 BLA::stop_loading_animation
-
-
 
 if [ $? -eq 1 ]; then
     echo "NixOS Failed to Rebuild."
     echo "Please check nixos-switch.log and the error message"
     exit 1
+else
+    echo "NixOS Rebuilt Successfully!" 
 fi
-
-echo "NixOS Rebuilt Successfully!" 
 
 read -p "Git Commit and Sync? " user_input
 
-currentDate=$(date +"SYS: %Y-%m-%d %H:%M:%S")
-
 if [[ $user_input =~ ^[Yy]$ ]]; then
-    git commit -m "$currentDate"
-    git push origin main
+    currentDate=$(date +"SYS: %Y-%m-%d %H:%M:%S")
+    git commit -m "$currentDate" &> git-commit.log
+    git push origin main &> git-sync.log
+    if [ $? -eq 1 ]; then
+        echo "Git failed to Commit and Sync."
+        echo "Please check git-commit.log git-sync.log for more details"
+        exit 1
+    else
+        echo "Git Commit and Sync Successfully!"
+    fi
 elif [[ $user_input =~ ^[Nn]$ ]]; then
-    echo "Configuration NOT backedup"
+    echo "Configuration not backed up."
 fi
 
 # 1. Enable sudo 
