SYS: 2025-06-09 21:49:39

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -21,7 +21,12 @@ read -p "Back it up? " user_input
 if [[ $user_input =~ ^[Yy]$ ]]; then
     git push origin main &> git-sync.log || 
         (git push origin main && exit 1)
-    echo "Configuration backed up :D"
+    if [ $? -ne 0 ]; then
+        echo "Configuration FAILED to back up :c"
+        exit 1
+    else
+        echo "Configuration backed up :D"
+    fi
 else
     echo "Configuration NOT backed up :c"
 fi
